
# dockerfile for php-apache webserver
# base image for building dockerfile
# lamp stack
FROM php:7.2.1-apache
# information about the maintainer to build this dockerfile
MAINTAINER usha<ushasri2810@gmail.com>
# extentions needed to use pdo and mysqli
RUN docker-php-ext-install pdo_mysql mysqli
